# -*- coding: utf-8 -*-
"""Guess the number game(computer).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7LvsJclfVi0lrqKnJSvMfV1uOS9I4gy
"""

import random

def guess_the_number():
  print("Welcome to the Guess the Number Game")
  print("I have chosen a number between 1 and 100")
  print("Can you guess what it is?")

  number_to_guess = random.randint(1, 100)

  guess = None
  attempts = 0

  while True:
   try:
      guess = int(input("Enter Your Guess"))

      attempts += 1
      if guess < number_to_guess:
          print("Too low! Try again")
      elif guess > number_to_guess:
          print("Too high! Try again")
      else:
        print(f"Congratulation! You've guessed the correct number in {attempts} attempts.")
        break
   except ValueError:
        print("Please Enter a Valid Number!.")
guess_the_number()